export const MASAI_JOB_REQUEST = "MASAI_JOB_REQUEST";
export const MASAI_JOB_SUCCESS = "MASAI_JOB_SUCCESS";
export const MASAI_JOB_FAILURE = "MASAI_JOB_FAILURE";

// filter by role

export const FILTER_JOB_REQUEST = "FILTER_JOB_REQUEST";
export const FILTER_JOB_SUCCESS = "FILTER_JOB_SUCCESS";
export const FILTER_JOB_FAILURE = "FILTER_JOB_FAILURE";